"""
test.py

Tests the generated zmachine_header.py parser against real Z-Machine story
files. Uses the ontology (zmachine_header.ttl) as the ground truth for what
fields should be present for a given version, rather than hardcoding
expectations.

For each story file provided, the script:

  1. Reads the version byte directly from the file (bypassing the parser)
     to establish the ground truth version.
  2. Queries the ontology to determine which fields and bits are expected
     for that version.
  3. Runs the parser and collects its output.
  4. Compares expected vs. actual, reporting missing fields, unexpected
     fields, and known tricky cases (Flags 1 split, font field swap,
     extension table).
  5. Prints a per-file report and a final summary table.

Usage:
    python test.py path/to/story1.z3 path/to/story2.z5 ...

    Or to test all zcode files in a directory:
    python test.py path/to/zcode_dir/

Requirements:
    - rdflib  (pip install rdflib)
    - zmachine_header.py  in the same directory as this script
      (generated by generate.py)
    - zmachine_header.ttl  in the same directory as this script
"""

import importlib.util
import sys

# import struct
from pathlib import Path
# from collections import defaultdict

from rdflib import Graph, URIRef  # , Literal
from rdflib.namespace import RDF, RDFS

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

SCRIPT_DIR = Path(__file__).parent
TTL_FILE = SCRIPT_DIR / "zmachine_header.ttl"
PARSER_FILE = SCRIPT_DIR / "zmachine_header.py"

# If automatic function discovery fails, set this to the exact function
# name used in the generated zmachine_header.py, e.g. "read_header"
PARSE_FUNCTION_NAME = None

ZM = "http://example.org/zmachine/"


def zm(local):
  return URIRef(ZM + local)


def short(uri):
  return str(uri).replace(ZM, "zm:")


# ---------------------------------------------------------------------------
# Load the ontology
# ---------------------------------------------------------------------------


def load_ontology() -> Graph:
  if not TTL_FILE.exists():
    print(f"[Error] Ontology not found: {TTL_FILE}", file=sys.stderr)
    sys.exit(1)
  g = Graph()
  g.parse(str(TTL_FILE), format="turtle")
  return g


# ---------------------------------------------------------------------------
# Load the generated parser as a module
# ---------------------------------------------------------------------------


def load_parser():
  if not PARSER_FILE.exists():
    print(
      f"[Error] Parser not found: {PARSER_FILE}\n        Run generate_parser.py first.",
      file=sys.stderr,
    )
    sys.exit(1)
  spec = importlib.util.spec_from_file_location("zmachine_header", PARSER_FILE)
  if spec is None or spec.loader is None:
    print(f"[Error] Could not load module spec from {PARSER_FILE}", file=sys.stderr)
    sys.exit(1)
  mod = importlib.util.module_from_spec(spec)
  spec.loader.exec_module(mod)
  return mod


# ---------------------------------------------------------------------------
# Ontology queries
# ---------------------------------------------------------------------------


def version_number(g: Graph, version_uri: URIRef) -> int:
  """Return the integer version number for a ZMachineVersion individual."""
  for val in g.objects(version_uri, zm("versionNumber")):
    return int(val)
  return 0


def fields_for_version(g: Graph, v: int) -> list[dict]:
  """
  Return all HeaderField (and FlagsRegister) individuals applicable for
  version v, excluding superseded fields.

  A field is applicable for version v if:
    - applicableFrom <= v
    - applicableUntil is absent OR applicableUntil >= v
  """
  results = []

  for field in g.subjects(RDF.type, zm("HeaderField")):
    # Also catches FlagsRegister (subclass), but we want to handle
    # FlagsRegister separately, so skip pure FlagsRegisters here
    # unless we want their offset too. We include them — bits are
    # checked separately.
    af_uri = next(g.objects(field, zm("applicableFrom")), None)
    au_uri = next(g.objects(field, zm("applicableUntil")), None)

    if af_uri is None:
      continue  # Malformed entry — skip

    af = version_number(g, af_uri)
    au = version_number(g, au_uri) if au_uri else 999

    if not (af <= v <= au):
      continue

    # Skip fields superseded by another (the superseding field will
    # appear as its own individual with its own applicableFrom)
    is_superseded = any(True for _ in g.subjects(zm("supersededBy"), field))
    if is_superseded:
      continue

    label = str(next(g.objects(field, RDFS.label), short(field)))
    offset = next(g.objects(field, zm("offset")), None)
    authority = next(g.objects(field, zm("hasSourceAuthority")), None)
    is_flags = (field, RDF.type, zm("FlagsRegister")) in g

    results.append(
      {
        "uri": field,
        "label": label,
        "offset": int(offset) if offset is not None else None,
        "normative": str(authority) == ZM + "normative",
        "is_flags": is_flags,
      }
    )

  return sorted(results, key=lambda x: x["offset"] or 0)


def bits_for_version(g: Graph, register_uri: URIRef, v: int) -> list[dict]:
  """
  Return all BitField individuals within a FlagsRegister that are
  applicable for version v.
  """
  results = []
  for bit in g.objects(register_uri, zm("containsBit")):
    af_uri = next(g.objects(bit, zm("applicableFrom")), None)
    au_uri = next(g.objects(bit, zm("applicableUntil")), None)

    if af_uri is None:
      continue

    af = version_number(g, af_uri)
    au = version_number(g, au_uri) if au_uri else 999

    if not (af <= v <= au):
      continue

    label = str(next(g.objects(bit, RDFS.label), short(bit)))
    pos = next(g.objects(bit, zm("bitPosition")), None)
    authority = next(g.objects(bit, zm("hasSourceAuthority")), None)

    results.append(
      {
        "uri": bit,
        "label": label,
        "bit_position": int(pos) if pos is not None else None,
        "normative": str(authority) == ZM + "normative",
      }
    )

  return sorted(results, key=lambda x: x["bit_position"] or 0)


def extension_fields_for_version(g: Graph, v: int) -> list[dict]:
  """Return all ExtensionField individuals applicable for version v."""
  results = []
  for ef in g.subjects(RDF.type, zm("ExtensionField")):
    af_uri = next(g.objects(ef, zm("applicableFrom")), None)
    if af_uri is None:
      continue
    af = version_number(g, af_uri)
    if af > v:
      continue

    label = str(next(g.objects(ef, RDFS.label), short(ef)))
    idx = next(g.objects(ef, zm("wordIndex")), None)
    results.append(
      {
        "uri": ef,
        "label": label,
        "word_index": int(idx) if idx is not None else None,
      }
    )

  return sorted(results, key=lambda x: x["word_index"] or 0)


def superseded_pairs(g: Graph) -> list[tuple]:
  """Return (superseded_label, superseding_label) pairs."""
  pairs = []
  for s, p, o in g.triples((None, zm("supersededBy"), None)):
    s_label = str(next(g.objects(s, RDFS.label), short(s)))
    o_label = str(next(g.objects(o, RDFS.label), short(o)))
    pairs.append((s_label, o_label))
  return pairs


# ---------------------------------------------------------------------------
# Tricky case checks
# These probe the specific version-conditional branching cases that reveal
# whether the parser genuinely used the ontology or just pattern-matched.
# ---------------------------------------------------------------------------


def check_flags1_split(parser_output: dict, v: int) -> list[str]:
  """
  Flags 1 at offset 0x01 has entirely different bit meanings in V1-3
  vs V4+. Check that the parser branched correctly.
  """
  issues = []
  flags1 = None

  # Parser may nest flags under various key names; try common ones
  for key in ("flags1", "flags_1", "Flags 1", "flags"):
    candidate = parser_output.get(key)
    if isinstance(candidate, dict):
      flags1 = candidate
      break

  # Also check inside a nested 'flags_registers' or similar group
  if flags1 is None:
    for val in parser_output.values():
      if isinstance(val, dict):
        for key in ("flags1", "flags_1", "Flags 1"):
          if key in val:
            flags1 = val[key]
            break

  if flags1 is None:
    issues.append("WARN: Could not locate Flags 1 in parser output — key name unclear")
    return issues

  if v <= 3:
    # Expect V1-3 bits: status line type (bit 1), split discs (bit 2),
    # status not available (bit 4), screen split (bit 5), var pitch (bit 6)
    v4_only_terms = ("bold", "italic", "fixed", "timed", "picture", "colour", "color")
    flat = str(flags1).lower()
    for term in v4_only_terms:
      if term in flat:
        issues.append(f"FAIL: Flags 1 contains V4+ term '{term}' but file is V{v}")
  else:
    # Expect V4+ bits: colours, bold, italic, fixed-space, timed input, etc.
    v13_only_terms = ("score/turns", "hours:min", "split across", "two disc")
    flat = str(flags1).lower()
    for term in v13_only_terms:
      if term in flat:
        issues.append(f"FAIL: Flags 1 contains V1-3 term '{term}' but file is V{v}")

  if not issues:
    issues.append("PASS: Flags 1 version split appears correct")

  return issues


def check_font_swap(parser_output: dict, v: int) -> list[str]:
  """
  At offsets 0x26/0x27, font width and height are swapped between V5
  and V6. The ontology models this with supersededBy. Check that the
  parser output uses the correct label for the correct version.
  """
  issues = []

  if v < 5:
    issues.append("SKIP: Font fields only present from V5")
    return issues

  # Flatten all string keys in the output for a broad search
  flat = str(parser_output).lower()

  # In V5: 0x26 should be width, 0x27 should be height
  # In V6: 0x26 should be height, 0x27 should be width
  # We look for both labels and flag if they appear in the wrong version
  if v == 5:
    if "font_width" in flat or "font width" in flat:
      issues.append("PASS: Font width label present in V5 output")
    else:
      issues.append("WARN: Could not confirm font width label in V5 output")
    if "font_height" in flat or "font height" in flat:
      issues.append("PASS: Font height label present in V5 output")
    else:
      issues.append("WARN: Could not confirm font height label in V5 output")

  if v == 6:
    # Both labels should appear but mapped to swapped offsets.
    # We can't easily check the offset mapping from the dict alone,
    # so we just confirm both are present and note the swap.
    if ("font_width" in flat or "font width" in flat) and (
      "font_height" in flat or "font height" in flat
    ):
      issues.append(
        "PASS: Both font dimension labels present in V6 output "
        "(manual check: 0x26=height, 0x27=width in V6)"
      )
    else:
      issues.append("WARN: One or both font dimension labels missing in V6 output")

  return issues


def check_extension_table(parser_output: dict, v: int) -> list[str]:
  """
  Extension table should be present for V5+ and absent (or gracefully
  handled) for V1-4.
  """
  issues = []

  flat_keys = set(str(k).lower() for k in parser_output.keys())
  has_ext = any(
    "extension" in k or "ext_" in k or "flags3" in k or "flags_3" in k
    for k in flat_keys
  )

  # Also check nested dicts
  for val in parser_output.values():
    if isinstance(val, dict):
      for k in val.keys():
        if "extension" in str(k).lower() or "flags3" in str(k).lower():
          has_ext = True

  if v < 5:
    if has_ext:
      issues.append(
        f"WARN: Extension table data present in V{v} output — "
        "should be absent or empty for pre-V5 files"
      )
    else:
      issues.append(f"PASS: No extension table in V{v} output (correct)")
  else:
    if has_ext:
      issues.append(f"PASS: Extension table present in V{v} output")
    else:
      issues.append(
        f"WARN: No extension table in V{v} output — "
        "expected for V5+ (may be absent if pointer is 0)"
      )

  return issues


def check_conventional_fields(parser_output: dict) -> list[str]:
  """
  Fields from Appendix B (release number, serial code, Inform version)
  should appear in the output, ideally under a 'conventional' key.
  """
  issues = []
  flat = str(parser_output).lower()

  conventional_terms = {
    "release": "release number (0x02)",
    "serial": "serial code (0x12)",
    "inform": "Inform compiler version (0x3C)",
  }

  has_conventional_key = "conventional" in flat

  for term, description in conventional_terms.items():
    if term in flat:
      issues.append(f"PASS: Conventional field present — {description}")
    else:
      issues.append(f"WARN: Conventional field missing — {description}")

  if has_conventional_key:
    issues.append("PASS: Output contains a 'conventional' grouping key")
  else:
    issues.append(
      "WARN: No 'conventional' grouping key — conventional fields "
      "may be mixed with normative fields"
    )

  return issues


# ---------------------------------------------------------------------------
# Parser function discovery
# ---------------------------------------------------------------------------


def _find_parse_function(mod):
  """
  Attempt to find the header-parsing callable in the generated module.

  Strategy (in order):
    1. Known conventional names.
    2. Any top-level callable whose name contains 'parse' or 'header'
       and whose annotation or default suggests it takes bytes.
    3. Any top-level callable that accepts exactly one positional argument,
       tested by calling it with a minimal 64-byte zeroed buffer to see
       if it returns a dict.

  Returns the callable, or None if nothing suitable is found.
  Also prints what was found to aid debugging.
  """
  import inspect

  # Step 1: conventional names
  candidates = [
    "parse_header",
    "parse",
    "read_header",
    "decode_header",
    "parse_zmachine_header",
    "read_zmachine_header",
  ]
  for name in candidates:
    fn = getattr(mod, name, None)
    if callable(fn):
      print(f"[test_parser] Found parse function by name: {name}")
      return fn

  # Step 2: name-based heuristic on all module-level callables
  for name, obj in inspect.getmembers(mod, inspect.isfunction):
    if any(kw in name.lower() for kw in ("parse", "header", "read", "decode")):
      print(f"[test_parser] Found parse function by name heuristic: {name}")
      return obj

  # Step 3: probe any single-argument callable with a dummy buffer
  dummy = bytes(64)
  for name, obj in inspect.getmembers(mod, inspect.isfunction):
    try:
      sig = inspect.signature(obj)
      params = [
        p for p in sig.parameters.values() if p.default is inspect.Parameter.empty
      ]
      if len(params) == 1:
        result = obj(dummy)
        if isinstance(result, dict):
          print(
            f"[test_parser] Found parse function by probe: {name} "
            f"(returns dict for dummy input)"
          )
          return obj
    except Exception:
      continue

  # Nothing found — report what is available
  all_fns = [name for name, _ in inspect.getmembers(mod, inspect.isfunction)]
  print(
    f"[test_parser] WARNING: Could not find a suitable parse function.\n"
    f"             Functions available in zmachine_header.py: {all_fns}\n"
    f"             Set PARSE_FUNCTION_NAME at the top of test_parser.py "
    f"to override.",
    file=sys.stderr,
  )
  return None


# ---------------------------------------------------------------------------
# Per-file test runner
# ---------------------------------------------------------------------------


def test_file(
  story_path: Path,
  g: Graph,
  parser_mod,
) -> dict:
  """
  Run all checks for a single story file.
  Returns a results dict with pass/warn/fail counts and per-check details.
  """
  result = {
    "path": story_path,
    "version": None,
    "parse_error": None,
    "field_coverage": [],
    "tricky_cases": [],
    "summary": {"pass": 0, "warn": 0, "fail": 0},
  }

  # --- Read raw bytes ---
  try:
    data = story_path.read_bytes()
  except OSError as e:
    result["parse_error"] = f"Could not read file: {e}"
    return result

  if len(data) < 64:
    result["parse_error"] = (
      f"File too short ({len(data)} bytes) — not a valid Z-Machine file"
    )
    return result

  # --- Determine version from raw bytes (ground truth) ---
  v = data[0]
  result["version"] = v

  if v < 1 or v > 6:
    result["parse_error"] = f"Unexpected version byte: {v}"
    return result

  # --- Run the parser ---
  parser_output = None
  try:
    # Allow manual override via module-level constant
    if PARSE_FUNCTION_NAME:
      parse_fn = getattr(parser_mod, PARSE_FUNCTION_NAME, None)
      if parse_fn is None:
        result["parse_error"] = (
          f"PARSE_FUNCTION_NAME='{PARSE_FUNCTION_NAME}' was set "
          f"but not found in zmachine_header.py"
        )
        return result
    else:
      parse_fn = _find_parse_function(parser_mod)

    if parse_fn is None:
      result["parse_error"] = (
        "Could not find a suitable parse function in zmachine_header.py. "
        "Set PARSE_FUNCTION_NAME at the top of test_parser.py to override."
      )
      return result

    parser_output = parse_fn(data)

  except Exception as e:
    result["parse_error"] = f"Parser raised exception: {type(e).__name__}: {e}"
    return result

  # --- Field coverage: ontology-derived expectations ---
  expected_fields = fields_for_version(g, v)
  flat_output = str(parser_output).lower()

  for field in expected_fields:
    label_lower = field["label"].lower()
    # Use key words from the label to search the output
    keywords = [
      w
      for w in label_lower.split()
      if len(w) > 3 and w not in ("field", "offset", "version", "table", "address")
    ]
    found = any(kw in flat_output for kw in keywords) if keywords else False
    authority = "normative" if field["normative"] else "conventional"
    status = "PASS" if found else "WARN"
    result["field_coverage"].append(
      f"{status} [{authority}] {field['label']} (offset 0x{field['offset']:02X})"
      if field["offset"] is not None
      else f"{status} [{authority}] {field['label']}"
    )

  # --- Tricky case checks ---
  result["tricky_cases"].extend(check_flags1_split(parser_output, v))
  result["tricky_cases"].extend(check_font_swap(parser_output, v))
  result["tricky_cases"].extend(check_extension_table(parser_output, v))
  result["tricky_cases"].extend(check_conventional_fields(parser_output))

  # --- Count pass/warn/fail ---
  all_checks = result["field_coverage"] + result["tricky_cases"]
  for line in all_checks:
    if line.startswith("PASS"):
      result["summary"]["pass"] += 1
    elif line.startswith("WARN"):
      result["summary"]["warn"] += 1
    elif line.startswith("FAIL"):
      result["summary"]["fail"] += 1

  return result


# ---------------------------------------------------------------------------
# Reporting
# ---------------------------------------------------------------------------


def print_result(result: dict):
  path = result["path"]
  v = result["version"]

  print()
  print("=" * 70)
  print(f"  File   : {path.name}")
  print(f"  Version: {v if v else '?'}")
  print("=" * 70)

  if result["parse_error"]:
    print(f"\n  [ERROR] {result['parse_error']}")
    return

  print("\n--- Field Coverage (ontology-derived expectations) ---")
  for line in result["field_coverage"]:
    print(f"  {line}")

  print("\n--- Tricky Case Checks ---")
  for line in result["tricky_cases"]:
    print(f"  {line}")

  s = result["summary"]
  print(f"\n  Summary: {s['pass']} PASS  |  {s['warn']} WARN  |  {s['fail']} FAIL")


def print_summary_table(results: list[dict]):
  print()
  print("=" * 70)
  print("  SUMMARY TABLE")
  print("=" * 70)
  print(f"  {'File':<30} {'V':>3}  {'PASS':>5}  {'WARN':>5}  {'FAIL':>5}  {'Status'}")
  print(f"  {'-' * 30}  {'-' * 3}  {'-' * 5}  {'-' * 5}  {'-' * 5}  {'-' * 10}")

  for r in results:
    name = r["path"].name[:30]
    v = str(r["version"]) if r["version"] else "?"
    if r["parse_error"]:
      print(f"  {name:<30} {v:>3}  {'':>5}  {'':>5}  {'':>5}  ERROR")
      continue
    s = r["summary"]
    status = (
      "OK"
      if s["fail"] == 0 and s["warn"] == 0
      else "WARN"
      if s["fail"] == 0
      else "FAIL"
    )
    print(
      f"  {name:<30} {v:>3}  {s['pass']:>5}  {s['warn']:>5}  {s['fail']:>5}  {status}"
    )

  print()
  versions_seen = sorted(set(r["version"] for r in results if r["version"]))
  print(f"  Versions tested: {versions_seen}")
  print(f"  Files tested   : {len(results)}")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def collect_story_files(args: list[str]) -> list[Path]:
  """Expand any directory arguments to all zcode files within them."""
  files = []
  zcode_extensions = {".z1", ".z2", ".z3", ".z4", ".z5", ".z6", ".z7", ".z8"}

  for arg in args:
    p = Path(arg)
    if p.is_dir():
      found = sorted(f for f in p.iterdir() if f.suffix.lower() in zcode_extensions)
      if not found:
        print(f"[Warning] No zcode files found in directory: {p}")
      files.extend(found)
    elif p.exists():
      files.append(p)
    else:
      print(f"[Warning] File not found, skipping: {p}")

  return files


def main():
  if len(sys.argv) < 2:
    print(
      "Usage: python test_parser.py <story.z3> [story.z5 ...]\n"
      "       python test_parser.py <directory_of_zcode_files/>"
    )
    sys.exit(1)

  story_files = collect_story_files(sys.argv[1:])

  if not story_files:
    print("[Error] No story files to test.")
    sys.exit(1)

  print(f"[test_parser] Loading ontology from {TTL_FILE.name}...")
  g = load_ontology()
  print(f"[test_parser] Loaded {len(g)} triples.")

  print(f"[test_parser] Loading parser from {PARSER_FILE.name}...")
  parser_mod = load_parser()
  print("[test_parser] Parser loaded.")

  print(f"\n[test_parser] Testing {len(story_files)} file(s)...\n")

  results = []
  for story_path in story_files:
    result = test_file(story_path, g, parser_mod)
    print_result(result)
    results.append(result)

  print_summary_table(results)


if __name__ == "__main__":
  main()
